const User = require('../../models/User');
const { generateLinkCode } = require('../../utils/database');

moon({
  name: 'link',
  category: 'general',
  description: 'Link WhatsApp account to Discord (persistent & real-time)',

  async execute(sock, jid, sender, args, m, db) {
    const code = args[0]?.toUpperCase();

    // Scenario 1: User types .link (without code) on WhatsApp -> Generate code for Discord
    if (!code) {
      try {
        let waUser = await User.findOne({ whatsappNumber: sender });
        if (!waUser) {
          waUser = new User({
            whatsappNumber: sender,
            username: sender.split('@')[0]
          });
        }

        if (waUser.discordId) {
          return sock.sendMessage(jid, {
            text: `✅ Your account is already linked to Discord ID: \`${waUser.discordId}\``
          });
        }

        const newCode = generateLinkCode();
        const expiry = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes

        waUser.linkCode = newCode;
        waUser.linkCodeExpiry = expiry;
        await waUser.save();

        return sock.sendMessage(jid, {
          text: `🔗 *Link Your Account*\n\nTo link your WhatsApp account with Discord, follow these steps:\n\n1. Go to Discord.\n2. Send the following command to the bot in DMs:\n   \`.link ${newCode}\`\n\n*This code will expire in 10 minutes.*`
        });
      } catch (err) {
        console.error('❌ Link generation error:', err);
        return sock.sendMessage(jid, { text: `❌ Failed to generate link code: ${err.message}` });
      }
    }

    // Scenario 2: User types .link <code> on WhatsApp -> Apply code from Discord
    try {
      // Find user by valid code (could be a Discord user who generated it)
      const linkedUser = await User.findOne({
        linkCode: code,
        linkCodeExpiry: { $gt: new Date() }
      });

      if (!linkedUser) {
        return sock.sendMessage(jid, {
          text: '❌ Invalid or expired linking code. Please generate a new one on Discord using `.link`.'
        });
      }

      // Find current WhatsApp user
      let waUser = await User.findOne({ whatsappNumber: sender });
      if (!waUser) {
        waUser = new User({
          whatsappNumber: sender,
          username: sender.split('@')[0]
        });
      }

      // Already linked check
      if (waUser.discordId) {
        return sock.sendMessage(jid, {
          text: '❌ This WhatsApp account is already linked to a Discord account.\nUse .unlink first before linking again.'
        });
      }

      // If the code was generated by a Discord user, link this WhatsApp account to that Discord user's document
      if (linkedUser.discordId && !linkedUser.whatsappNumber) {
        // Merge data if waUser has any (optional, but good for consistency)
        linkedUser.balance = (linkedUser.balance || 0) + (waUser.balance || 0);
        linkedUser.whatsappNumber = sender;
        linkedUser.linkCode = undefined;
        linkedUser.linkCodeExpiry = undefined;
        await linkedUser.save();

        // Delete the temporary waUser if it's a different document
        if (waUser._id.toString() !== linkedUser._id.toString()) {
          await User.deleteOne({ _id: waUser._id });
        }

        return sock.sendMessage(jid, {
          text: '✅ *Linked Successfully*\n\nYour WhatsApp and Discord accounts are now connected.\nYour data is now shared across both platforms.'
        });
      }

      return sock.sendMessage(jid, { text: '❌ Invalid linking flow. Please try again.' });

    } catch (err) {
      console.error('❌ Link error:', err);
      return sock.sendMessage(jid, { text: `❌ Linking failed:\n${err.message}` });
    }
  }
});
